// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// 102 # 1 "com/donhatchsw/util/FuzzyPointHashTable.prejava"
// 103 # 1 "<built-in>"
// 104 # 1 "<command-line>"
// 105 # 1 "com/donhatchsw/util/FuzzyPointHashTable.prejava"
/* vim: set filetype=java: */
/*
* Copyright (c) 2005,2006 Don Hatch Software
*/

package com.donhatchsw.util;

/**
*  Spatial hash table where the key is a double[], with fuzzy equality.
*  <p>
*  Two doubles a,b are considered equal if |a-b| &le; littleTol,
*  and unequal if |a-b| &gt; bigTol.
*  If a pair of doubles is encountered that are neither equal
*  nor unequal (i.e. their difference is in the forbidden range (littleTol,bigTol] ),
*  then a FuzzyException is thrown.
*  <p>
*  Two double[]s are considered equal if all their coords are equal (using
*  the above fuzzy definition of equal),
*  and unequal if any of their coords are unequal
*  (or if the arrays have different sizes).
*  If a pair of double[]s is encountered that are neither equal
*  nor unequal, then a FuzzyException is thrown.
*  <p>
*  Depends on classes:
*  <ul>
*       <li> VecMath </li>
*       <li> Arrays </li>
*  </ul>
* XXX only depends indirectly on Arrays, and only uses VecMath.toString();
* XXX that dependency could be easily removed.
*/

// Doesn't derived from anything,
// because I only felt like implementing a small number of methods (get and put).
public class FuzzyPointHashTable<V>
{
    private double bucketSize;
    private double littleTol;
    private double bigTol;
    private double tol; // (littleTol+bigTol)/2
    private double invBucketSize; // 1./bucketSize
    private java.util.HashMap<FuzzyPoint,V> hashtable;

    /**
    * Construct a fuzzy point hash table.
    *
    * The params are required to satisfy:
    * <pre>
    *     0 &le; littleTol &le; bigTol &le; bucketSize/1,000,000</pre>
    * BucketSize should be chosen somewhere around the smallest distance
    * ever expected between two distinct points, so that it would be
    * surprising if two or more points ever fell into the same bucket;
    * this is not strictly required but the hash table will not be efficient
    * if too many points end up in a single bucket.
    * However; bucketSize must be much much larger than bigTol.
    *
    * The following are typical values:
    * <pre>
    *     littleTol=1e-12
    *     bigTol=1e-10
    *     bucketSize=1/1024.
    * </pre>
    */
    public FuzzyPointHashTable(double littleTol,
                               double bigTol,
                               double bucketSize)
    {
        // Input restriction: 0 <= littleTol <= bigTol <= bucketSize/1,000,000
        if (!(0 <= littleTol))
            throw new IllegalArgumentException("FuzzyPointHashTable: littleTol = "+littleTol+", must be >= 0");
        if (!(littleTol <= bigTol))
            throw new IllegalArgumentException("FuzzyPointHashTable: littleTol = "+littleTol+", bigTol = "+bigTol+", out of order");
        //if (!(1e6*bigTol <= bucketSize))
        if (!(1e4*bigTol <= bucketSize))
            throw new IllegalArgumentException("FuzzyPointHashTable: bigTol = "+bigTol+", bucketSize = "+bucketSize+", bucketSize is not enough bigger than bigTol");

        this.bucketSize = bucketSize;
        this.littleTol = littleTol;
        this.bigTol = bigTol;

        this.tol = (littleTol+bigTol)*.5;
        this.invBucketSize = 1./bucketSize;

        this.hashtable = new java.util.HashMap<FuzzyPoint,V>();
    } // ctor

    private class FuzzyPoint
    {
        private double point[];
        public FuzzyPoint(double point[])
        {
            this.point = point;
        }
        @SuppressWarnings("unchecked") // TODO: get rid of this if possible
        public boolean equals(Object that)
        {
            double thatPoint[] = ((FuzzyPoint)that).point;
            if (point.length != thatPoint.length)
                return false;
            boolean someonesBiggerThanLittleTol = false;
            for (int i = 0; i < point.length; ++i)
            {
                double diff = Math.abs(point[i]-thatPoint[i]);
                if (diff > bigTol)
                    return false;
                if (diff > littleTol)
                    someonesBiggerThanLittleTol = true;
            }
            if (someonesBiggerThanLittleTol)
            {
                throw new FuzzyException("FuzzyPoint.equals: "+VecMath.toString(point)+" is neither equal nor unequal to "+VecMath.toString(thatPoint)+", using littleTol="+littleTol+", bigTol="+bigTol+"");
            }
            return true;
        } // equals
        public int hashCode()
        {
            int hash = 47;
            for (int i = 0; i < point.length; ++i)
            {
                //
                // We know coord is now in the interval
                //     [gridLine-bigTol, gridLine+bucketSize-bigTol),
                // give or take a bit or so of floating point roundoff error.
                //
                // Check the fuzziness assumption, which says, additionally,
                // that coord must be in either the closed interval:
                //     [gridLine-littleTol, gridLine+littleTol]
                // or the open interval:
                //     (gridLine+bigTol, gridLine+bucketSize-bigTol).
                // i.e. it can't be in either of the forbidden zones
                //     [gridLine-bigTol, gridLine-littleTol)
                // or  (gridLine+littleTol, gridLine+bigTol].
                //
                // I.e. the real line is partitioned into:
                //     (-infinity, gridLine-bigTol)                  impossible
                //     [gridLine-bigTol, gridLine-littleTol)         illegal
                //     [gridLine-littleTol, gridLine+littleTol]      legal
                //     (gridLine+littleTol, gridLine+bigTol]         illegal
                //     (gridLine+bigTol, gridLine+bucketSize-bigTol) legal
                //     [gridLine+bucketSize-bigTol, infinity)        impossible
                //
                //                 illegal
                //                 |   legal
                //                 |   |   illegal
                //                 |   |   |
                //   impossible )[   )[|](   ](    legal    )[ impossible
                //               |    |||    |               |
                //               |    |||    |               gridLine+bucketSize-bigTol
                //               |    |||    gridLine+bigTol
                //               |    ||gridLine+littleTol
                //               |    |gridLine
                //               |    gridLine-littleTol
                //               gridLine-bigTol
                double coord = point[i];
                int gridIndex = (int)Math.floor((coord+bigTol) * invBucketSize);
                double gridLine = gridIndex * bucketSize;

                double diff = Math.abs(coord - gridLine);
                if (littleTol < diff && diff <= bigTol)
                    throw new FuzzyException("FuzzyPoint.hashCode: coord "+coord+" is neither equal nor unequal to grid line "+gridLine+", using littleTol="+littleTol+", bigTol="+bigTol+", bucketSize="+bucketSize+"    diff="+diff);
                hash = hash*3 + gridIndex;
            }
            return hash;
        } // hashCode
    } // private class FuzzyPoint


    private FuzzyPoint scratchForGet = new FuzzyPoint(new double[0]);

    /**
    * Gets the value assocated with key, or null if there is none.
    **/
    public V get(double key[])
    {
        scratchForGet.point = key; // XXX hey, why can I do this? scratchForGet.point is supposed to be private!!!
        return hashtable.get(scratchForGet);
    }

    /**
    * Puts the value into the table with given key (assumed immutable),
    * returning the previous value (or null if there was none)
    */
    public V put(double key[],
                 V value)
    {
        return hashtable.put(new FuzzyPoint(key), value);
    }

    /**
    * Gets thrown when the fuzzyiness assumption is violated.
    * The fuzziness assumption is that for any two points a,b,
    * the max-norm-distance between a and b
    * is either &le; littleTol, or &gt; bigTol.
    * I.e. this exception gets thrown if any max-norm
    * distance between two points is in the forbidden interval (littleTol, bigTol].
    */
    @SuppressWarnings("serial")
    public static class FuzzyException extends RuntimeException
    {
        FuzzyException(String description)
        {
            super(description);
        }
    } // FuzzyException

} // class FuzzyPointHashTable
